# Generated by Django 4.1.7 on 2023-03-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cater', '0002_alter_package_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
