# Generated by Django 4.1.7 on 2023-03-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cater', '0003_alter_package_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
    ]
