# Generated by Django 4.1.7 on 2023-03-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cater', '0006_debaniers_pizza_place_kamuketha_pork_joint_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Debaniers_Pizza_Place',
        ),
        migrations.DeleteModel(
            name='Kamuketha_pork_joint',
        ),
        migrations.DeleteModel(
            name='Mama_Africa_company',
        ),
        migrations.DeleteModel(
            name='Mini_Inn_Hotel',
        ),
        migrations.DeleteModel(
            name='Panesic_Hotel',
        ),
        migrations.DeleteModel(
            name='Quivers_Bar_Grill',
        ),
        migrations.AddField(
            model_name='package',
            name='charging_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='package',
            name='phone',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='team_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
