# Generated by Django 4.1.7 on 2023-03-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cater", "0008_package_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
